@baseURL = http://localhost:3000
@startDate=2019-12-27T09:00:00.926Z
@endDate= 2020-03-19T09:00:00.926Z
@startPrice=33.63
@endPrice=39.34

@samplePlanets=["sun", "moon"]

GET {{baseURL}}

###

POST {{baseURL}}/ephemeris/move-planets-by-price-range
Content-Type: application/json

{
  "startDate":"{{startDate}}",
  "endDate": "{{endDate}}",
  "startPrice":"{{startPrice}}",
  "endPrice":"{{endPrice}}",
  "movePlanetsFromStartOfTheRange": false
}

###

POST {{baseURL}}/ephemeris/move-planets-by-price-range
Content-Type: application/json

{
  "startDate":"{{startDate}}",
  "endDate": "{{endDate}}",
  "startPrice":"{{startPrice}}",
  "endPrice":"{{endPrice}}",
  "planets": {{samplePlanets}},
  "movePlanetsFromStartOfTheRange": false
}

###

POST {{baseURL}}/price/project-time-with-sq9
Content-Type: application/json

{
  "startPrice":"{{startPrice}}",
  "endPrice":"{{endPrice}}"
}

###