@baseURL = http://localhost:3000/ephemeris
@startDate= 2015-01-24T09:00:00.926Z
@endDate= 2015-11-04T09:00:00.926Z
@startPrice=5
@endPrice=7.5

@samplePlanets=["sun", "moon"]

GET {{baseURL}}

###

POST {{baseURL}}/price-range HTTP/1.1
Content-Type: application/json

{
  "startDate":"{{startDate}}",
  "endDate": "{{endDate}}",
  "startPrice":"{{startPrice}}",
  "endPrice":"{{endPrice}}",
  "planets": {{samplePlanets}},
  "movePlanetsFromStartOfTheRange": false
}

###