declare module 'swisseph' {
  export type CalculationResult = {
    distance: number;
    distanceSpeed: number;
    latitude: number;
    latitudeSpeed: number;
    longitude: number;
    longitudeSpeed: number;
    rflag: number;
  };

  namespace swisseph {
    namespace ephemeris {
      const swisseph = 2;
      const moshier = 4;
      const de200 = 'de200.eph';
      const de405 = 'de405.eph';
      const de406 = 'de406.eph';
      const de406e = 'de406e.eph';
      const de414 = 'de414.eph';
      const de421 = 'de421.eph';
      const de422 = 'de422.eph';
      const de430 = 'de430.eph';
      const de431 = 'de431.eph';
    }

    const SEFLG_ASTROMETRIC = 1536;
    const SEFLG_BARYCTR = 16384;
    const SEFLG_DEFAULTEPH = 2;
    const SEFLG_DPSIDEPS_1980 = 262144;
    const SEFLG_EQUATORIAL = 2048;
    const SEFLG_HELCTR = 8;
    const SEFLG_ICRS = 131072;
    const SEFLG_J2000 = 32;
    const SEFLG_JPLEPH = 1;
    const SEFLG_JPLHOR = 262144;
    const SEFLG_JPLHOR_APPROX = 524288;
    const SEFLG_MOSEPH = 4;
    const SEFLG_NOABERR = 1024;
    const SEFLG_NOGDEFL = 512;
    const SEFLG_NONUT = 64;
    const SEFLG_ORBEL_AA = 32768;
    const SEFLG_RADIANS = 8192;
    const SEFLG_SIDEREAL = 65536;
    const SEFLG_SPEED = 256;
    const SEFLG_SPEED3 = 128;
    const SEFLG_SWIEPH = 2;
    const SEFLG_TOPOCTR = 32768;
    const SEFLG_TRUEPOS = 16;
    const SEFLG_XYZ = 4096;
    const SE_ACRONYCHAL_RISING = 5;
    const SE_ACRONYCHAL_SETTING = 6;
    const SE_ADMETOS = 45;
    const SE_APOLLON = 44;
    const SE_APP_TO_TRUE = 1;
    const SE_ARMC = 2;
    const SE_ASC = 0;
    const SE_AST_OFFSET = 10000;
    const SE_AUNIT_TO_KM = 149597870.7;
    const SE_AUNIT_TO_LIGHTYEAR = 0.000015812507409819728;
    const SE_AUNIT_TO_PARSEC = 0.000004848136811095274;
    const SE_BIT_ASTRO_TWILIGHT = 4096;
    const SE_BIT_CIVIL_TWILIGHT = 1024;
    const SE_BIT_DISC_BOTTOM = 8192;
    const SE_BIT_DISC_CENTER = 256;
    const SE_BIT_FIXED_DISC_SIZE = 16384;
    const SE_BIT_GEOCTR_NO_ECL_LAT = 128;
    const SE_BIT_NAUTIC_TWILIGHT = 2048;
    const SE_BIT_NO_REFRACTION = 512;
    const SE_CALC_ITRANSIT = 8;
    const SE_CALC_MTRANSIT = 4;
    const SE_CALC_RISE = 1;
    const SE_CALC_SET = 2;
    const SE_CERES = 17;
    const SE_CHIRON = 15;
    const SE_COASC1 = 5;
    const SE_COASC2 = 6;
    const SE_COMET_OFFSET = 1000;
    const SE_COSMICAL_SETTING = 6;
    const SE_CUPIDO = 40;
    const SE_EARTH = 14;
    const SE_ECL2HOR = 0;
    const SE_ECL_1ST_VISIBLE = 512;
    const SE_ECL_2ND_VISIBLE = 1024;
    const SE_ECL_3RD_VISIBLE = 2048;
    const SE_ECL_4TH_VISIBLE = 4096;
    const SE_ECL_ALLTYPES_LUNAR = 84;
    const SE_ECL_ALLTYPES_SOLAR = 63;
    const SE_ECL_ANNULAR = 8;
    const SE_ECL_ANNULAR_TOTAL = 32;
    const SE_ECL_CENTRAL = 1;
    const SE_ECL_MAX_VISIBLE = 256;
    const SE_ECL_NONCENTRAL = 2;
    const SE_ECL_NUT = -1;
    const SE_ECL_OCC_BEG_DAYLIGHT = 8192;
    const SE_ECL_OCC_END_DAYLIGHT = 16384;
    const SE_ECL_ONE_TRY = 32768;
    const SE_ECL_PARTBEG_VISIBLE = 512;
    const SE_ECL_PARTEND_VISIBLE = 4096;
    const SE_ECL_PARTIAL = 16;
    const SE_ECL_PENUMBBEG_VISIBLE = 8192;
    const SE_ECL_PENUMBEND_VISIBLE = 16384;
    const SE_ECL_PENUMBRAL = 64;
    const SE_ECL_TOTAL = 4;
    const SE_ECL_TOTBEG_VISIBLE = 1024;
    const SE_ECL_TOTEND_VISIBLE = 2048;
    const SE_ECL_VISIBLE = 128;
    const SE_EQU2HOR = 1;
    const SE_EQUASC = 4;
    const SE_EVENING_FIRST = 3;
    const SE_EVENING_LAST = 2;
    const SE_FICT_MAX = 999;
    const SE_FICT_OFFSET = 40;
    const SE_FICT_OFFSET_1 = 39;
    const SE_FIXSTAR = -10;
    const SE_GREG_CAL = 1;
    const SE_HADES = 41;
    const SE_HARRINGTON = 50;
    const SE_HELFLAG_AVKIND = 491520;
    const SE_HELFLAG_AVKIND_MIN7 = 131072;
    const SE_HELFLAG_AVKIND_MIN9 = 262144;
    const SE_HELFLAG_AVKIND_PTO = 65536;
    const SE_HELFLAG_AVKIND_VR = 32768;
    const SE_HELFLAG_HIGH_PRECISION = 256;
    const SE_HELFLAG_LONG_SEARCH = 128;
    const SE_HELFLAG_NO_DETAILS = 1024;
    const SE_HELFLAG_OPTICAL_PARAMS = 512;
    const SE_HELFLAG_SEARCH_1_PERIOD = 2048;
    const SE_HELFLAG_VISLIM_DARK = 4096;
    const SE_HELFLAG_VISLIM_NOMOON = 8192;
    const SE_HELFLAG_VISLIM_PHOTOPIC = 16384;
    const SE_HELIACAL_RISING = 1;
    const SE_HELIACAL_SETTING = 2;
    const SE_HOR2ECL = 0;
    const SE_HOR2EQU = 1;
    const SE_INTP_APOG = 21;
    const SE_INTP_PERG = 22;
    const SE_ISIS = 48;
    const SE_JUL_CAL = 0;
    const SE_JUNO = 19;
    const SE_JUPITER = 5;
    const SE_KRONOS = 43;
    const SE_MARS = 4;
    const SE_MAX_STNAME = 256;
    const SE_MC = 1;
    const SE_MEAN_APOG = 12;
    const SE_MEAN_NODE = 10;
    const SE_MERCURY = 2;
    const SE_MIXEDOPIC_FLAG = 2;
    const SE_MOON = 1;
    const SE_MORNING_FIRST = 1;
    const SE_MORNING_LAST = 4;
    const SE_NALL_NAT_POINTS = 38;
    const SE_NASCMC = 8;
    const SE_NEPTUNE = 8;
    const SE_NEPTUNE_ADAMS = 52;
    const SE_NEPTUNE_LEVERRIER = 51;
    const SE_NFICT_ELEM = 15;
    const SE_NIBIRU = 49;
    const SE_NODBIT_FOPOINT = 256;
    const SE_NODBIT_MEAN = 1;
    const SE_NODBIT_OSCU = 2;
    const SE_NODBIT_OSCU_BAR = 4;
    const SE_NPLANETS = 23;
    const SE_NSIDM_PREDEF = 43;
    const SE_OSCU_APOG = 13;
    const SE_PALLAS = 18;
    const SE_PHOLUS = 16;
    const SE_PHOTOPIC_FLAG = 0;
    const SE_PLUTO = 9;
    const SE_PLUTO_LOWELL = 53;
    const SE_PLUTO_PICKERING = 54;
    const SE_POLASC = 7;
    const SE_POSEIDON = 47;
    const SE_PROSERPINA = 57;
    const SE_SATURN = 6;
    const SE_SCOTOPIC_FLAG = 1;
    const SE_SIDBITS = 256;
    const SE_SIDBIT_ECL_T0 = 256;
    const SE_SIDBIT_SSY_PLANE = 512;
    const SE_SIDBIT_USER_UT = 1024;
    const SE_SIDM_ALDEBARAN_15TAU = 14;
    const SE_SIDM_ARYABHATA = 23;
    const SE_SIDM_ARYABHATA_522 = 37;
    const SE_SIDM_ARYABHATA_MSUN = 24;
    const SE_SIDM_B1950 = 20;
    const SE_SIDM_BABYL_BRITTON = 38;
    const SE_SIDM_BABYL_ETPSC = 13;
    const SE_SIDM_BABYL_HUBER = 12;
    const SE_SIDM_BABYL_KUGLER1 = 9;
    const SE_SIDM_BABYL_KUGLER2 = 10;
    const SE_SIDM_BABYL_KUGLER3 = 11;
    const SE_SIDM_DELUCE = 2;
    const SE_SIDM_DJWHAL_KHUL = 6;
    const SE_SIDM_FAGAN_BRADLEY = 0;
    const SE_SIDM_GALALIGN_MARDYKS = 34;
    const SE_SIDM_GALCENT_0SAG = 17;
    const SE_SIDM_GALCENT_COCHRANE = 40;
    const SE_SIDM_GALCENT_MULA_WILHELM = 36;
    const SE_SIDM_GALCENT_RGILBRAND = 30;
    const SE_SIDM_GALEQU_FIORENZA = 41;
    const SE_SIDM_GALEQU_IAU1958 = 31;
    const SE_SIDM_GALEQU_MULA = 33;
    const SE_SIDM_GALEQU_TRUE = 32;
    const SE_SIDM_HIPPARCHOS = 15;
    const SE_SIDM_J1900 = 19;
    const SE_SIDM_J2000 = 18;
    const SE_SIDM_JN_BHASIN = 8;
    const SE_SIDM_KRISHNAMURTI = 5;
    const SE_SIDM_LAHIRI = 1;
    const SE_SIDM_RAMAN = 3;
    const SE_SIDM_SASSANIAN = 16;
    const SE_SIDM_SS_CITRA = 26;
    const SE_SIDM_SS_REVATI = 25;
    const SE_SIDM_SURYASIDDHANTA = 21;
    const SE_SIDM_SURYASIDDHANTA_MSUN = 22;
    const SE_SIDM_TRUE_CITRA = 27;
    const SE_SIDM_TRUE_MULA = 35;
    const SE_SIDM_TRUE_PUSHYA = 29;
    const SE_SIDM_TRUE_REVATI = 28;
    const SE_SIDM_TRUE_SHEORAN = 39;
    const SE_SIDM_USER = 255;
    const SE_SIDM_USHASHASHI = 4;
    const SE_SIDM_VALENS_MOON = 42;
    const SE_SIDM_YUKTESHWAR = 7;
    const SE_SPLIT_DEG_KEEP_DEG = 32;
    const SE_SPLIT_DEG_KEEP_SIGN = 16;
    const SE_SPLIT_DEG_NAKSHATRA = 1024;
    const SE_SPLIT_DEG_ROUND_DEG = 4;
    const SE_SPLIT_DEG_ROUND_MIN = 2;
    const SE_SPLIT_DEG_ROUND_SEC = 1;
    const SE_SPLIT_DEG_ZODIACAL = 8;
    const SE_SUN = 0;
    const SE_TRUE_NODE = 11;
    const SE_TRUE_TO_APP = 0;
    const SE_URANUS = 7;
    const SE_VARUNA = 30000;
    const SE_VENUS = 3;
    const SE_VERTEX = 3;
    const SE_VESTA = 20;
    const SE_VULCAN = 55;
    const SE_VULKANUS = 46;
    const SE_WALDEMATH = 58;
    const SE_WHITE_MOON = 56;
    const SE_ZEUS = 42;
    const SIMULATE_VICTORVB = 1;
    const TJD_INVALID = 99999999;

    function calc(options, callback): any;
    function swe_azalt(): any;
    function swe_azalt_rev(): any;
    function swe_calc(): any;
    function swe_calc_ut(
      julianDate,
      planetCode: number,
      flag,
      callaba,
    ): CalculationResult;

    function swe_close(): any;
    function swe_cotrans(): any;
    function swe_cotrans_sp(): any;
    function swe_cs2degstr(): any;
    function swe_cs2lonlatstr(): any;
    function swe_cs2timestr(): any;
    function swe_csnorm(): any;
    function swe_csroundsec(): any;
    function swe_d2l(): any;
    function swe_date_conversion(): any;
    function swe_day_of_week(): any;
    function swe_deg_midp(): any;
    function swe_degnorm(): any;
    function swe_deltat(): any;
    function swe_difcs2n(): any;
    function swe_difcsn(): any;
    function swe_difdeg2n(): any;
    function swe_difdegn(): any;
    function swe_difrad2n(): any;
    function swe_fixstar(): any;
    function swe_fixstar2(): any;
    function swe_fixstar2_mag(): any;
    function swe_fixstar2_ut(): any;
    function swe_fixstar_mag(): any;
    function swe_fixstar_ut(): any;
    function swe_gauquelin_sector(): any;
    function swe_get_ayanamsa(): any;
    function swe_get_ayanamsa_ex(): any;
    function swe_get_ayanamsa_ex_ut(): any;
    function swe_get_ayanamsa_name(): any;
    function swe_get_ayanamsa_ut(): any;
    function swe_get_orbital_elements(): any;
    function swe_get_planet_name(): any;
    function swe_get_tid_acc(): any;
    function swe_heliacal_pheno_ut(): any;
    function swe_heliacal_ut(): any;
    function swe_houses(): any;
    function swe_houses_armc(): any;
    function swe_houses_ex(): any;
    function swe_houses_pos(): any;
    function swe_jdet_to_utc(): any;
    function swe_jdut1_to_utc(): any;
    function swe_julday(
      year: number,
      month: number,
      day: number,
      hour: number,
      calendar: number,
      callback: (result: any) => void,
    ): any;

    function swe_lun_eclipse_how(): any;
    function swe_lun_eclipse_when(): any;
    function swe_lun_eclipse_when_loc(): any;
    function swe_lun_occult_when_glob(): any;
    function swe_lun_occult_when_loc(): any;
    function swe_lun_occult_where(): any;
    function swe_nod_aps(): any;
    function swe_nod_aps_ut(): any;
    function swe_orbit_max_min_true_distance(): any;
    function swe_pheno(): any;
    function swe_pheno_ut(): any;
    function swe_rad_midp(): any;
    function swe_radnorm(): any;
    function swe_refrac(): any;
    function swe_refrac_extended(): any;
    function swe_revjul(): any;
    function swe_rise_trans(): any;
    function swe_rise_trans_true_hor(): any;
    function swe_set_ephe_path(): any;
    function swe_set_jpl_file(): any;
    function swe_set_lapse_rate(): any;
    function swe_set_sid_mode(): any;
    function swe_set_tid_acc(): any;
    function swe_set_topo(): any;
    function swe_sidtime(): any;
    function swe_sidtime0(): any;
    function swe_sol_eclipse_how(): any;
    function swe_sol_eclipse_when_glob(): any;
    function swe_sol_eclipse_when_loc(): any;
    function swe_sol_eclipse_where(): any;
    function swe_split_deg(): any;
    function swe_time_equ(): any;
    function swe_utc_time_zone(): any;
    function swe_utc_to_jd(): any;
    function swe_version(): any;
    function swe_vis_limit_mag(): any;
  }

  export default swisseph;
}
